"""dept and desig FK

Revision ID: 86c6eaea8622
Revises: c70eb0b20193
Create Date: 2025-09-27 23:31:37.039044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c6eaea8622'
down_revision: Union[str, Sequence[str], None] = 'c70eb0b20193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_documents')
    op.add_column('onboarding_sessions', sa.Column('designation_id', sa.Integer(), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'onboarding_sessions', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'onboarding_sessions', 'designations', ['designation_id'], ['id'])
    op.drop_column('onboarding_sessions', 'department')
    op.drop_column('onboarding_sessions', 'hashed_password')
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.drop_column('users', 'profile_picure_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picure_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_picture_url')
    op.add_column('onboarding_sessions', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onboarding_sessions', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'onboarding_sessions', type_='foreignkey')
    op.drop_constraint(None, 'onboarding_sessions', type_='foreignkey')
    op.drop_column('onboarding_sessions', 'department_id')
    op.drop_column('onboarding_sessions', 'designation_id')
    op.create_table('onboarding_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_template_id'], ['document_templates.id'], name=op.f('onboarding_documents_document_template_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], name=op.f('onboarding_documents_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_documents_pkey'))
    )
    # ### end Alembic commands ###
