"""Initial migration establishing baseline

Revision ID: c70eb0b20193
Revises: 
Create Date: 2025-09-24 18:06:21.032886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70eb0b20193'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_documents')
    op.drop_column('onboarding_sessions', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_sessions', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('onboarding_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_template_id'], ['document_templates.id'], name=op.f('onboarding_documents_document_template_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], name=op.f('onboarding_documents_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_documents_pkey'))
    )
    # ### end Alembic commands ###
